### ISSUE TITLE
TypeError: expected a character buffer object

### ISSUE THREAD

**Issue by lelutin** [delvelabs/tachyon#10]
Hey there,

I just tried to run tachyon.py on my web site and got a crash. Here's the output that I got:

```
     Tachyon v2.0.0-beta10 - Fast Multi-Threaded Web Discovery Tool
     https://github.com/initnull/tachyon

[03:11:23] [INFO] Starting Discovery on lelutin.ca
[03:11:23] [INFO] Fetching session cookie
[03:11:23] [INFO] Benchmarking root 404
[03:11:23] [INFO] Loading target paths
[03:11:23] [INFO] Loading target files
[03:11:23] [INFO] Executing 4 host plugins
[03:11:23] [INFO]  - Robots Plugin: /robots.txt not found on target site
[03:11:23] [INFO]  - PathGenerator Plugin: added 66 computer generated path.
[03:11:23] [INFO]  - PathGenerator Plugin: added 36 computer generated files.
[03:11:23] [INFO]  - HostProcessor Plugin: added 7 new filenames
[03:11:23] [INFO]  - Svn Plugin: Searching for /.svn/entries
Traceback (most recent call last):
  File "./tachyon.py", line 469, in <module>
[03:11:23] [INFO]  - Svn Plugin: no /.svn/entries found
    test_paths_exists()
  File "./tachyon.py", line 96, in test_paths_exists
    dbutils.add_path_to_fetch_queue(path)
  File "/home/gabster/dev/tachyon/core/dbutils.py", line 33, in add_path_to_fetch_queue
    url_string = _get_cached_url_string(url_obj)
  File "/home/gabster/dev/tachyon/core/dbutils.py", line 25, in _get_cached_url_string
    return url_obj['url'].translate({'/' : None})
TypeError: expected a character buffer object
```

some version info:

```
$ git describe 
1.0-Stable-57-g3fcfecd
# ^ this is current master
$ python --version
Python 2.7.9
$ dpkg -l | grep urllib3
ii  python-urllib3                        1.9.1-3                               all          HTTP library with thread-safe connection pooling for Python
```

**Comment by ppepos** [comment]
This is caused by using python3's `str.translate()` [here](https://github.com/gabtremblay/tachyon/blob/3fcfecd25ee05687fc0ad60ed46a2d306282e63b/core/dbutils.py#L25). I will open a pull-request to suggest a fix.

**Comment by gabtremblay** [comment]
Fixed before the repo transfer (a while ago ;))
